version: "3.9"

services:
  server:
    container_name: chat-nest-server
    env_file: .env
    build:
      tags:
        - "amirmuha/chat-server-dev"
      context: .
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - "${PORT}:4200"
    volumes:
      - ./:/usr/app/
    restart: on-failure
    depends_on: 
      - postgres
    networks: 
      - chat-system
      - auth-system

  postgres:
    container_name: chat-nest-postgresql
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-changeme}"
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks: 
      - chat-system
      - auth-system

networks:
  chat-system:
  auth-system:
    external:
      name: auth-system
volumes:
  db: 
    name: chat-nest-db
