version: "3.9"

services:
  server:
    container_name: chat-nest-server
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - "${PORT:-4200}:4200"
    volumes:
      - ./:/usr/app/
    restart: unless-stopped
    depends_on: 
      - postgres

  postgres:
    container_name: chat-nest-postgresql
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-changeme}"
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  pgadmin:
    container_name: chat-nest-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80/tcp"
    restart: unless-stopped
    depends_on: 
      - postgres

volumes:
  db: 
    name: chat-nest-db
  pgadmin: 
    name: chat-nest-pgadmin
